package dasm

// Table containing IX instructions (DD prefix)
var ddInstructions = []*instruction{
	0x09: {mnemonic: "ADD  IX,BC", size: 2},
	0x19: {mnemonic: "ADD  IX,DE", size: 2},
	0x21: {mnemonic: "LD   IX,$1$2", args: []int{3, 2}, size: 4},
	0x22: {mnemonic: "LD   ($1$2),IX", args: []int{3, 2}, size: 4},
	0x23: {mnemonic: "INC  IX", size: 2},
	0x24: {mnemonic: "INC  IXH", size: 2},
	0x25: {mnemonic: "DEC  IXH", size: 2},
	0x26: {mnemonic: "LD   IXH,$1", args: []int{2}, size: 3},
	0x29: {mnemonic: "ADD  IX,IX", size: 2},
	0x2A: {mnemonic: "LD   IX,($1$2)", args: []int{3, 2}, size: 4},
	0x2B: {mnemonic: "DEC  IX", size: 2},
	0x2C: {mnemonic: "INC  IXL", size: 2},
	0x2D: {mnemonic: "DEC  IXL", size: 2},
	0x2E: {mnemonic: "LD   IXL,$1", args: []int{2}, size: 3},
	0x34: {mnemonic: "INC  (IX+$1)", args: []int{2}, size: 3},
	0x35: {mnemonic: "DEC  (IX)", size: 2},
	0x36: {mnemonic: "LD   (IX+$1),$2", args: []int{3, 2}, size: 4},
	0x39: {mnemonic: "ADD  IX,SP", size: 2},
	0x44: {mnemonic: "LD   B,IXH", size: 2},
	0x45: {mnemonic: "LD   B,IXL", size: 2},
	0x46: {mnemonic: "LD   B,(IX+$1)", args: []int{2}, size: 3},
	0x4C: {mnemonic: "LD   C,IXH", size: 2},
	0x4D: {mnemonic: "LD   C,IXL", size: 2},
	0x4E: {mnemonic: "LD   C,(IX+$1)", args: []int{2}, size: 3},
	0x54: {mnemonic: "LD   D,IXH", size: 2},
	0x55: {mnemonic: "LD   D,IXL", size: 2},
	0x56: {mnemonic: "LD   D,(IX+$1)", args: []int{2}, size: 3},
	0x5C: {mnemonic: "LD   E,IXH", size: 2},
	0x5D: {mnemonic: "LD   E,IXL", size: 2},
	0x5E: {mnemonic: "LD   E,(IX+$1)", args: []int{2}, size: 3},
	0x60: {mnemonic: "LD   IXH,B", size: 2},
	0x61: {mnemonic: "LD   IXH,C", size: 2},
	0x62: {mnemonic: "LD   IXH,D", size: 2},
	0x63: {mnemonic: "LD   IXH,E", size: 2},
	0x64: {mnemonic: "LD   IXH,IXH", size: 2},
	0x65: {mnemonic: "LD   IXH,IXL", size: 2},
	0x66: {mnemonic: "LD   H,(IX+$1)", args: []int{2}, size: 3},
	0x67: {mnemonic: "LD   IXH,A", size: 2},
	0x68: {mnemonic: "LD   IXL,B", size: 2},
	0x69: {mnemonic: "LD   IXL,C", size: 2},
	0x6A: {mnemonic: "LD   IXL,D", size: 2},
	0x6B: {mnemonic: "LD   IXL,E", size: 2},
	0x6C: {mnemonic: "LD   IXL,IXH", size: 2},
	0x6D: {mnemonic: "LD   IXL,IXL", size: 2},
	0x6E: {mnemonic: "LD   L,(IX+$1)", args: []int{2}, size: 3},
	0x6F: {mnemonic: "LD   IXL,A", size: 2},
	0x70: {mnemonic: "LD   (IX+$1),B", args: []int{2}, size: 3},
	0x71: {mnemonic: "LD   (IX+$1),C", args: []int{2}, size: 3},
	0x72: {mnemonic: "LD   (IX+$1),D", args: []int{2}, size: 3},
	0x73: {mnemonic: "LD   (IX+$1),E", args: []int{2}, size: 3},
	0x74: {mnemonic: "LD   (IX+$1),H", args: []int{2}, size: 3},
	0x75: {mnemonic: "LD   (IX+$1),L", args: []int{2}, size: 3},
	0x77: {mnemonic: "LD   (IX+$1),A", args: []int{2}, size: 3},
	0x7C: {mnemonic: "LD   A,IXH", size: 2},
	0x7D: {mnemonic: "LD   A,IXL", size: 2},
	0x7E: {mnemonic: "LD   A,(IX+$1)", args: []int{2}, size: 3},
	0x84: {mnemonic: "ADD  A,IXH", size: 2},
	0x85: {mnemonic: "ADD  A,IXL", size: 2},
	0x86: {mnemonic: "ADD  A,(IX+$1)", args: []int{2}, size: 3},
	0x8C: {mnemonic: "ADC  A,IXH", size: 2},
	0x8D: {mnemonic: "ADC  A,IXL", size: 2},
	0x8E: {mnemonic: "ADC  A,(IX+$1)", args: []int{2}, size: 3},
	0x94: {mnemonic: "SUB  IXH", size: 2},
	0x95: {mnemonic: "SUB  IXL", size: 2},
	0x96: {mnemonic: "SUB  (IX+$1)", args: []int{2}, size: 3},
	0x9C: {mnemonic: "SBC  A,IXH", size: 2},
	0x9D: {mnemonic: "SBC  A,IXL", size: 2},
	0x9E: {mnemonic: "SBC  A,(IX+$1)", args: []int{2}, size: 3},
	0xA4: {mnemonic: "AND  IXH", size: 2},
	0xA5: {mnemonic: "AND  IXL", size: 2},
	0xA6: {mnemonic: "AND  (IX+$1)", args: []int{2}, size: 3},
	0xAC: {mnemonic: "XOR  IXH", size: 2},
	0xAD: {mnemonic: "XOR  IXL", size: 2},
	0xAE: {mnemonic: "XOR  (IX+$1)", args: []int{2}, size: 3},
	0xB4: {mnemonic: "OR   IXH", size: 2},
	0xB5: {mnemonic: "OR   IXL", size: 2},
	0xB6: {mnemonic: "OR   (IX+$1)", args: []int{2}, size: 3},
	0xBC: {mnemonic: "CP   IXH", size: 2},
	0xBD: {mnemonic: "CP   IXL", size: 2},
	0xBE: {mnemonic: "CP   (IX+$1)", args: []int{2}, size: 3},
	0xE1: {mnemonic: "POP  IX", size: 2},
	0xE3: {mnemonic: "EX   (SP),IX", size: 2},
	0xE5: {mnemonic: "PUSH IX", size: 2},
	0xE9: {mnemonic: "JP   (IX)", size: 2},
	0xF9: {mnemonic: "LD   SP,IX", size: 2},
	0xFF: nil,
}
