package dasm

// Table containing extended instructions (ED prefix)
var edInstructions = []*instruction{
	0x40: {mnemonic: "IN   B,(C)"},
	0x41: {mnemonic: "OUT  (C),B"},
	0x42: {mnemonic: "SBC  HL,BC"},
	0x43: {mnemonic: "LD   ($1$2),BC", args: 2},
	0x44: {mnemonic: "NEG"},
	0x45: {mnemonic: "RETN"},
	0x46: {mnemonic: "IM   0"},
	0x47: {mnemonic: "LD   I,A"},
	0x48: {mnemonic: "IN   C,(C)"},
	0x49: {mnemonic: "OUT  (C),C"},
	0x4A: {mnemonic: "ADC  HL,BC"},
	0x4B: {mnemonic: "LD   BC,($1$2)", args: 2},
	0x4C: {mnemonic: "NEG"},
	0x4D: {mnemonic: "RETI"},
	0x4E: {mnemonic: "IM   0/1"},
	0x4F: {mnemonic: "LD   R,A"},
	0x50: {mnemonic: "IN   D,(C)"},
	0x51: {mnemonic: "OUT  (C),D"},
	0x52: {mnemonic: "SBC  HL,DE"},
	0x53: {mnemonic: "LD   ($1$2),DE", args: 2},
	0x54: {mnemonic: "NEG"},
	0x55: {mnemonic: "RETN"},
	0x56: {mnemonic: "IM   1"},
	0x57: {mnemonic: "LD   A,I"},
	0x58: {mnemonic: "IN   E,(C)"},
	0x59: {mnemonic: "OUT  (C),E"},
	0x5A: {mnemonic: "ADC  HL,DE"},
	0x5B: {mnemonic: "LD   DE,($1$2)", args: 2},
	0x5C: {mnemonic: "NEG"},
	0x5D: {mnemonic: "RETN"},
	0x5E: {mnemonic: "IM   2"},
	0x5F: {mnemonic: "LD   A,R"},
	0x60: {mnemonic: "IN   H,(C)"},
	0x61: {mnemonic: "OUT  (C),H"},
	0x62: {mnemonic: "SBC  HL,HL"},
	0x63: {mnemonic: "LD   ($1$2),HL", args: 2},
	0x64: {mnemonic: "NEG"},
	0x65: {mnemonic: "RETN"},
	0x67: {mnemonic: "RRD"},
	0x68: {mnemonic: "IN   L,(C)"},
	0x69: {mnemonic: "OUT  (C),L"},
	0x6A: {mnemonic: "ADC  HL,HL"},
	0x6B: {mnemonic: "LD   HL,($1$2)", args: 2},
	0x6C: {mnemonic: "NEG"},
	0x6D: {mnemonic: "RETN"},
	0x6E: {mnemonic: "IM   0/1"},
	0x6F: {mnemonic: "RLD"},
	0x70: {mnemonic: "IN   (C)"},
	0x71: {mnemonic: "OUT  (C),0"},
	0x72: {mnemonic: "SBC  HL,SP"},
	0x73: {mnemonic: "LD   ($1$2),SP", args: 2},
	0x74: {mnemonic: "NEG"},
	0x75: {mnemonic: "RETN"},
	0x78: {mnemonic: "IN   A,(C)"},
	0x79: {mnemonic: "OUT  (C),A"},
	0x7A: {mnemonic: "ADC  HL,SP"},
	0x7B: {mnemonic: "LD   SP,($1$2)", args: 2},
	0x7C: {mnemonic: "NEG"},
	0x7D: {mnemonic: "RETN"},
	0xA0: {mnemonic: "LDI"},
	0xA1: {mnemonic: "CPI"},
	0xA2: {mnemonic: "INI"},
	0xA3: {mnemonic: "OUTI"},
	0xA8: {mnemonic: "LDD"},
	0xA9: {mnemonic: "CPD"},
	0xAA: {mnemonic: "IND"},
	0xAB: {mnemonic: "OUTD"},
	0xB0: {mnemonic: "LDIR"},
	0xB1: {mnemonic: "CPIR"},
	0xB2: {mnemonic: "INIR"},
	0xB3: {mnemonic: "OTIR"},
	0xB8: {mnemonic: "LDDR"},
	0xB9: {mnemonic: "CPDR"},
	0xBA: {mnemonic: "INDR"},
	0xBB: {mnemonic: "OTDR"},
	0xFF: nil,
}
