package dasm

// Table containing IY instructions (FD prefix)
var fdInstructions = []*instruction{
	0x09: {mnemonic: "ADD  IY,BC"},
	0x19: {mnemonic: "ADD  IY,DE"},
	0x21: {mnemonic: "LD   IY,$1$2", args: 2},
	0x22: {mnemonic: "LD   ($1$2),IY", args: 2},
	0x23: {mnemonic: "INC  IY"},
	0x24: {mnemonic: "INC  IYH"},
	0x25: {mnemonic: "DEC  IYH"},
	0x26: {mnemonic: "LD   IYH,$1", args: 1},
	0x29: {mnemonic: "ADD  IY,IY"},
	0x2A: {mnemonic: "LD   IY,($1$2)", args: 2},
	0x2B: {mnemonic: "DEC  IY"},
	0x2C: {mnemonic: "INC  IYL"},
	0x2D: {mnemonic: "DEC  IYL"},
	0x2E: {mnemonic: "LD   IYL,$1", args: 1},
	0x34: {mnemonic: "INC  (IY+$1)", args: 1},
	0x35: {mnemonic: "DEC  (IY)"},
	0x36: {mnemonic: "LD   (IY+$2),$1", args: 2},
	0x39: {mnemonic: "ADD  IY,SP"},
	0x44: {mnemonic: "LD   B,IYH"},
	0x45: {mnemonic: "LD   B,IYL"},
	0x46: {mnemonic: "LD   B,(IY+$1)", args: 1},
	0x4C: {mnemonic: "LD   C,IYH"},
	0x4D: {mnemonic: "LD   C,IYL"},
	0x4E: {mnemonic: "LD   C,(IY+$1)", args: 1},
	0x54: {mnemonic: "LD   D,IYH"},
	0x55: {mnemonic: "LD   D,IYL"},
	0x56: {mnemonic: "LD   D,(IY+$1)", args: 1},
	0x5C: {mnemonic: "LD   E,IYH"},
	0x5D: {mnemonic: "LD   E,IYL"},
	0x5E: {mnemonic: "LD   E,(IY+$1)", args: 1},
	0x60: {mnemonic: "LD   IYH,B"},
	0x61: {mnemonic: "LD   IYH,C"},
	0x62: {mnemonic: "LD   IYH,D"},
	0x63: {mnemonic: "LD   IYH,E"},
	0x64: {mnemonic: "LD   IYH,IYH"},
	0x65: {mnemonic: "LD   IYH,IYL"},
	0x66: {mnemonic: "LD   H,(IY+$1)", args: 1},
	0x67: {mnemonic: "LD   IYH,A"},
	0x68: {mnemonic: "LD   IYL,B"},
	0x69: {mnemonic: "LD   IYL,C"},
	0x6A: {mnemonic: "LD   IYL,D"},
	0x6B: {mnemonic: "LD   IYL,E"},
	0x6C: {mnemonic: "LD   IYL,IYH"},
	0x6D: {mnemonic: "LD   IYL,IYL"},
	0x6E: {mnemonic: "LD   L,(IY+$1)", args: 1},
	0x6F: {mnemonic: "LD   IYL,A"},
	0x70: {mnemonic: "LD   (IY+$1),B", args: 1},
	0x71: {mnemonic: "LD   (IY+$1),C", args: 1},
	0x72: {mnemonic: "LD   (IY+$1),D", args: 1},
	0x73: {mnemonic: "LD   (IY+$1),E", args: 1},
	0x74: {mnemonic: "LD   (IY+$1),H", args: 1},
	0x75: {mnemonic: "LD   (IY+$1),L", args: 1},
	0x77: {mnemonic: "LD   (IY+$1),A", args: 1},
	0x7C: {mnemonic: "LD   A,IYH"},
	0x7D: {mnemonic: "LD   A,IYL"},
	0x7E: {mnemonic: "LD   A,(IY+$1)", args: 1},
	0x84: {mnemonic: "ADD  A,IYH"},
	0x85: {mnemonic: "ADD  A,IYL"},
	0x86: {mnemonic: "ADD  A,(IY+$1)", args: 1},
	0x8C: {mnemonic: "ADC  A,IYH"},
	0x8D: {mnemonic: "ADC  A,IYL"},
	0x8E: {mnemonic: "ADC  A,(IY+$1)", args: 1},
	0x94: {mnemonic: "SUB  IYH"},
	0x95: {mnemonic: "SUB  IYL"},
	0x96: {mnemonic: "SUB  (IY+$1)", args: 1},
	0x9C: {mnemonic: "SBC  A,IYH"},
	0x9D: {mnemonic: "SBC  A,IYL"},
	0x9E: {mnemonic: "SBC  A,(IY+$1)", args: 1},
	0xA4: {mnemonic: "AND  IYH"},
	0xA5: {mnemonic: "AND  IYL"},
	0xA6: {mnemonic: "AND  (IY+$1)", args: 1},
	0xAC: {mnemonic: "XOR  IYH"},
	0xAD: {mnemonic: "XOR  IYL"},
	0xAE: {mnemonic: "XOR  (IY+$1)", args: 1},
	0xB4: {mnemonic: "OR   IYH"},
	0xB5: {mnemonic: "OR   IYL"},
	0xB6: {mnemonic: "OR   (IY+$1)", args: 1},
	0xBC: {mnemonic: "CP   IYH"},
	0xBD: {mnemonic: "CP   IYL"},
	0xBE: {mnemonic: "CP   (IY+$1)", args: 1},
	0xE1: {mnemonic: "POP  IY"},
	0xE3: {mnemonic: "EX   (SP),IY"},
	0xE5: {mnemonic: "PUSH IY"},
	0xE9: {mnemonic: "JP   (IY)"},
	0xF9: {mnemonic: "LD   SP,IY"},
	0xFF: nil,
}
