package dasm

// Table containing primary instructions
var primaryInstructions = []*instruction{
	0x00: {mnemonic: "NOP", size: 1},
	0x01: {mnemonic: "LD   BC,$1$2", args: []int{2, 1}, size: 3},
	0x02: {mnemonic: "LD   (BC),A", size: 1},
	0x03: {mnemonic: "INC  BC", size: 1},
	0x04: {mnemonic: "INC  B", size: 1},
	0x05: {mnemonic: "DEC  B", size: 1},
	0x06: {mnemonic: "LD   B,$1", args: []int{1}, size: 2},
	0x07: {mnemonic: "RLCA", size: 1},
	0x08: {mnemonic: "EX   AF,AF'", size: 1},
	0x09: {mnemonic: "ADD  HL,BC", size: 1},
	0x0A: {mnemonic: "LD   A,(BC)", size: 1},
	0x0B: {mnemonic: "DEC  BC", size: 1},
	0x0C: {mnemonic: "INC  C", size: 1},
	0x0D: {mnemonic: "DEC  C", size: 1},
	0x0E: {mnemonic: "LD   C,$1", args: []int{1}, size: 2},
	0x0F: {mnemonic: "RRCA", size: 1},
	0x10: {mnemonic: "DJNZ $1", args: []int{1}, size: 2},
	0x11: {mnemonic: "LD   DE,$1$2", args: []int{2, 1}, size: 3},
	0x12: {mnemonic: "LD   (DE),A", size: 1},
	0x13: {mnemonic: "INC  DE", size: 1},
	0x14: {mnemonic: "INC  D", size: 1},
	0x15: {mnemonic: "DEC  D", size: 1},
	0x16: {mnemonic: "LD   D,$1", args: []int{1}, size: 2},
	0x17: {mnemonic: "RLA", size: 1},
	0x18: {mnemonic: "JR   $1", args: []int{1}, size: 2},
	0x19: {mnemonic: "ADD  HL,DE", size: 1},
	0x1A: {mnemonic: "LD   A,(BC)", size: 1},
	0x1B: {mnemonic: "DEC  DE", size: 1},
	0x1C: {mnemonic: "INC  C", size: 1},
	0x1D: {mnemonic: "DEC  C", size: 1},
	0x1E: {mnemonic: "LD   C,$1", args: []int{1}, size: 2},
	0x1F: {mnemonic: "RRA", size: 1},
	0x20: {mnemonic: "JR NZ,$1", args: []int{1}, size: 2},
	0x21: {mnemonic: "LD   HL,$1$2", args: []int{2, 1}, size: 3},
	0x22: {mnemonic: "LD   ($1$2),HL", args: []int{2, 1}, size: 3},
	0x23: {mnemonic: "INC  HL", size: 1},
	0x24: {mnemonic: "INC  H", size: 1},
	0x25: {mnemonic: "DEC  H", size: 1},
	0x26: {mnemonic: "LD   H,$1", args: []int{1}, size: 2},
	0x27: {mnemonic: "DAA", size: 1},
	0x28: {mnemonic: "JR   Z,$1", args: []int{1}, size: 2},
	0x29: {mnemonic: "ADD  HL,HL", size: 1},
	0x2A: {mnemonic: "LD   HL,($1$2)", args: []int{2, 1}, size: 3},
	0x2B: {mnemonic: "DEC  HL", size: 1},
	0x2C: {mnemonic: "INC  L", size: 1},
	0x2D: {mnemonic: "DEC  L", size: 1},
	0x2E: {mnemonic: "LD   L,$1", args: []int{1}, size: 2},
	0x2F: {mnemonic: "CPL", size: 1},
	0x30: {mnemonic: "JR   NC,$1", args: []int{1}, size: 2},
	0x31: {mnemonic: "LD   SP,$1$2", args: []int{2, 1}, size: 3},
	0x32: {mnemonic: "LD   ($1$2),A", args: []int{2, 1}, size: 3},
	0x33: {mnemonic: "INC  SP", size: 1},
	0x34: {mnemonic: "INC  (HL)", size: 1},
	0x35: {mnemonic: "DEC  (HL)", size: 1},
	0x36: {mnemonic: "LD   (HL),$1", args: []int{1}, size: 2},
	0x37: {mnemonic: "SCF", size: 1},
	0x38: {mnemonic: "JR   C,$1", args: []int{1}, size: 2},
	0x39: {mnemonic: "ADD  HL,SP", size: 1},
	0x3A: {mnemonic: "LD   A,($1$2)", args: []int{2, 1}, size: 3},
	0x3B: {mnemonic: "DEC  SP", size: 1},
	0x3C: {mnemonic: "INC  A", size: 1},
	0x3D: {mnemonic: "DEC  A", size: 1},
	0x3E: {mnemonic: "LD   A,$1", args: []int{1}, size: 2},
	0x3F: {mnemonic: "CCF", size: 1},
	0x40: {mnemonic: "LD   B,B", size: 1},
	0x41: {mnemonic: "LD   B,C", size: 1},
	0x42: {mnemonic: "LD   B,D", size: 1},
	0x43: {mnemonic: "LD   B,E", size: 1},
	0x44: {mnemonic: "LD   B,H", size: 1},
	0x45: {mnemonic: "LD   B,L", size: 1},
	0x46: {mnemonic: "LD   B,(HL)", size: 1},
	0x47: {mnemonic: "LD   B,A", size: 1},
	0x48: {mnemonic: "LD   C,B", size: 1},
	0x49: {mnemonic: "LD   C,C", size: 1},
	0x4A: {mnemonic: "LD   C,D", size: 1},
	0x4B: {mnemonic: "LD   C,E", size: 1},
	0x4C: {mnemonic: "LD   C,H", size: 1},
	0x4D: {mnemonic: "LD   C,L", size: 1},
	0x4E: {mnemonic: "LD   C,(HL)", size: 1},
	0x4F: {mnemonic: "LD   C,A", size: 1},
	0x50: {mnemonic: "LD   D,B", size: 1},
	0x51: {mnemonic: "LD   D,C", size: 1},
	0x52: {mnemonic: "LD   D,D", size: 1},
	0x53: {mnemonic: "LD   D,E", size: 1},
	0x54: {mnemonic: "LD   D,H", size: 1},
	0x55: {mnemonic: "LD   D,L", size: 1},
	0x56: {mnemonic: "LD   D,(HL)", size: 1},
	0x57: {mnemonic: "LD   D,A", size: 1},
	0x58: {mnemonic: "LD   E,B", size: 1},
	0x59: {mnemonic: "LD   E,C", size: 1},
	0x5A: {mnemonic: "LD   E,D", size: 1},
	0x5B: {mnemonic: "LD   E,E", size: 1},
	0x5C: {mnemonic: "LD   E,H", size: 1},
	0x5D: {mnemonic: "LD   E,L", size: 1},
	0x5E: {mnemonic: "LD   E,(HL)", size: 1},
	0x5F: {mnemonic: "LD   E,A", size: 1},
	0x60: {mnemonic: "LD   H,B", size: 1},
	0x61: {mnemonic: "LD   H,C", size: 1},
	0x62: {mnemonic: "LD   H,D", size: 1},
	0x63: {mnemonic: "LD   H,E", size: 1},
	0x64: {mnemonic: "LD   H,H", size: 1},
	0x65: {mnemonic: "LD   H,L", size: 1},
	0x66: {mnemonic: "LD   H,(HL)", size: 1},
	0x67: {mnemonic: "LD   H,A", size: 1},
	0x68: {mnemonic: "LD   L,B", size: 1},
	0x69: {mnemonic: "LD   L,C", size: 1},
	0x6A: {mnemonic: "LD   L,D", size: 1},
	0x6B: {mnemonic: "LD   L,E", size: 1},
	0x6C: {mnemonic: "LD   L,H", size: 1},
	0x6D: {mnemonic: "LD   L,L", size: 1},
	0x6E: {mnemonic: "LD   L,(HL)", size: 1},
	0x6F: {mnemonic: "LD   L,A", size: 1},
	0x70: {mnemonic: "LD   (HL),B", size: 1},
	0x71: {mnemonic: "LD   (HL),C", size: 1},
	0x72: {mnemonic: "LD   (HL),D", size: 1},
	0x73: {mnemonic: "LD   (HL),E", size: 1},
	0x74: {mnemonic: "LD   (HL),H", size: 1},
	0x75: {mnemonic: "LD   (HL),L", size: 1},
	0x76: {mnemonic: "HALT", size: 1},
	0x77: {mnemonic: "LD   (HL),A", size: 1},
	0x78: {mnemonic: "LD   A,B", size: 1},
	0x79: {mnemonic: "LD   A,C", size: 1},
	0x7A: {mnemonic: "LD   A,D", size: 1},
	0x7B: {mnemonic: "LD   A,E", size: 1},
	0x7C: {mnemonic: "LD   A,H", size: 1},
	0x7D: {mnemonic: "LD   A,L", size: 1},
	0x7E: {mnemonic: "LD   A,(HL)", size: 1},
	0x7F: {mnemonic: "LD   A,A", size: 1},
	0x80: {mnemonic: "ADD  A,B", size: 1},
	0x81: {mnemonic: "ADD  A,C", size: 1},
	0x82: {mnemonic: "ADD  A,D", size: 1},
	0x83: {mnemonic: "ADD  A,E", size: 1},
	0x84: {mnemonic: "ADD  A,H", size: 1},
	0x85: {mnemonic: "ADD  A,L", size: 1},
	0x86: {mnemonic: "ADD  A,(HL)", size: 1},
	0x87: {mnemonic: "ADD  A,A", size: 1},
	0x88: {mnemonic: "ADC  A,B", size: 1},
	0x89: {mnemonic: "ADC  A,C", size: 1},
	0x8A: {mnemonic: "ADC  A,D", size: 1},
	0x8B: {mnemonic: "ADC  A,E", size: 1},
	0x8C: {mnemonic: "ADC  A,H", size: 1},
	0x8D: {mnemonic: "ADC  A,L", size: 1},
	0x8E: {mnemonic: "ADC  A,(HL)", size: 1},
	0x8F: {mnemonic: "ADC  A,A", size: 1},
	0x90: {mnemonic: "SUB  B", size: 1},
	0x91: {mnemonic: "SUB  C", size: 1},
	0x92: {mnemonic: "SUB  D", size: 1},
	0x93: {mnemonic: "SUB  E", size: 1},
	0x94: {mnemonic: "SUB  H", size: 1},
	0x95: {mnemonic: "SUB  L", size: 1},
	0x96: {mnemonic: "SUB  (HL)", size: 1},
	0x97: {mnemonic: "SUB  A", size: 1},
	0x98: {mnemonic: "SBC  A,B", size: 1},
	0x99: {mnemonic: "SBC  A,C", size: 1},
	0x9A: {mnemonic: "SBC  A,D", size: 1},
	0x9B: {mnemonic: "SBC  A,E", size: 1},
	0x9C: {mnemonic: "SBC  A,H", size: 1},
	0x9D: {mnemonic: "SBC  A,L", size: 1},
	0x9E: {mnemonic: "SBC  A,(HL)", size: 1},
	0x9F: {mnemonic: "SBC  A,A", size: 1},
	0xA0: {mnemonic: "AND  B", size: 1},
	0xA1: {mnemonic: "AND  C", size: 1},
	0xA2: {mnemonic: "AND  D", size: 1},
	0xA3: {mnemonic: "AND  E", size: 1},
	0xA4: {mnemonic: "AND  H", size: 1},
	0xA5: {mnemonic: "AND  L", size: 1},
	0xA6: {mnemonic: "AND  (HL)", size: 1},
	0xA7: {mnemonic: "AND  A", size: 1},
	0xA8: {mnemonic: "XOR  B", size: 1},
	0xA9: {mnemonic: "XOR  C", size: 1},
	0xAA: {mnemonic: "XOR  D", size: 1},
	0xAB: {mnemonic: "XOR  E", size: 1},
	0xAC: {mnemonic: "XOR  H", size: 1},
	0xAD: {mnemonic: "XOR  L", size: 1},
	0xAE: {mnemonic: "XOR  (HL)", size: 1},
	0xAF: {mnemonic: "XOR  A", size: 1},
	0xB0: {mnemonic: "OR   B", size: 1},
	0xB1: {mnemonic: "OR   C", size: 1},
	0xB2: {mnemonic: "OR   D", size: 1},
	0xB3: {mnemonic: "OR   E", size: 1},
	0xB4: {mnemonic: "OR   H", size: 1},
	0xB5: {mnemonic: "OR   L", size: 1},
	0xB6: {mnemonic: "OR   (HL)", size: 1},
	0xB7: {mnemonic: "OR   A", size: 1},
	0xB8: {mnemonic: "CP   B", size: 1},
	0xB9: {mnemonic: "CP   C", size: 1},
	0xBA: {mnemonic: "CP   D", size: 1},
	0xBB: {mnemonic: "CP   E", size: 1},
	0xBC: {mnemonic: "CP   H", size: 1},
	0xBD: {mnemonic: "CP   L", size: 1},
	0xBE: {mnemonic: "CP   (HL)", size: 1},
	0xBF: {mnemonic: "CP   A", size: 1},
	0xC0: {mnemonic: "RET  NZ", size: 1},
	0xC1: {mnemonic: "POP  BC", size: 1},
	0xC2: {mnemonic: "JP   NZ,$1$2", args: []int{2, 1}, size: 3},
	0xC3: {mnemonic: "JP   $1$2", args: []int{2, 1}, size: 3},
	0xC4: {mnemonic: "CALL NZ,$1$2", args: []int{2, 1}, size: 3},
	0xC5: {mnemonic: "PUSH BC", size: 1},
	0xC6: {mnemonic: "ADD  A,$1", args: []int{1}, size: 2},
	0xC7: {mnemonic: "RST  0h", size: 1},
	0xC8: {mnemonic: "RET  Z", size: 1},
	0xC9: {mnemonic: "RET", size: 1},
	0xCA: {mnemonic: "JP   Z,$1$2", args: []int{2, 1}, size: 3},
	0xCC: {mnemonic: "CALL Z,$1$2", args: []int{2, 1}, size: 3},
	0xCD: {mnemonic: "CALL $1$2", args: []int{2, 1}, size: 3},
	0xCE: {mnemonic: "ADC  A,$1", args: []int{1}, size: 2},
	0xCF: {mnemonic: "RST  08h", size: 1},
	0xD0: {mnemonic: "RET  NC", size: 1},
	0xD1: {mnemonic: "POP  DE", size: 1},
	0xD2: {mnemonic: "JP   NC,$1$2", args: []int{2, 1}, size: 3},
	0xD3: {mnemonic: "OUT  ($1),A", args: []int{1}, size: 2},
	0xD4: {mnemonic: "CALL NC,$1$2", args: []int{2, 1}, size: 3},
	0xD5: {mnemonic: "PUSH DE", size: 1},
	0xD6: {mnemonic: "SUB  $1", args: []int{1}, size: 2},
	0xD7: {mnemonic: "RST  10h", size: 1},
	0xD8: {mnemonic: "RET  C", size: 1},
	0xD9: {mnemonic: "EXX", size: 1},
	0xDA: {mnemonic: "JP   C,$1$2", args: []int{2, 1}, size: 3},
	0xDB: {mnemonic: "IN   A,($1)", args: []int{1}, size: 2},
	0xDC: {mnemonic: "CALL C,$1$2", args: []int{2, 1}, size: 3},
	0xDE: {mnemonic: "SBC  A,$1", args: []int{1}, size: 2},
	0xDF: {mnemonic: "RST  18h", size: 1},
	0xE0: {mnemonic: "RET  PO", size: 1},
	0xE1: {mnemonic: "POP  HL", size: 1},
	0xE2: {mnemonic: "JP   PO,$1$2", args: []int{2, 1}, size: 3},
	0xE3: {mnemonic: "EX   (SP),HL", size: 1},
	0xE4: {mnemonic: "CALL PO,$1$2", args: []int{2, 1}, size: 3},
	0xE5: {mnemonic: "PUSH HL", size: 1},
	0xE6: {mnemonic: "AND  $1", args: []int{1}, size: 2},
	0xE7: {mnemonic: "RST  20h", size: 1},
	0xE8: {mnemonic: "RET  PE", size: 1},
	0xE9: {mnemonic: "JP   (HL)", size: 1},
	0xEA: {mnemonic: "JP   PE,$1$2", args: []int{2, 1}, size: 3},
	0xEB: {mnemonic: "EX   DE,HL", size: 1},
	0xEC: {mnemonic: "CALL PE,$1$2", args: []int{2, 1}, size: 3},
	0xEE: {mnemonic: "XOR  $1", args: []int{1}, size: 2},
	0xEF: {mnemonic: "RST  28h", size: 1},
	0xF0: {mnemonic: "RET  P", size: 1},
	0xF1: {mnemonic: "POP  AF", size: 1},
	0xF2: {mnemonic: "JP   P,$1$2", args: []int{2, 1}, size: 3},
	0xF3: {mnemonic: "DI", size: 1},
	0xF4: {mnemonic: "CALL P,$1$2", args: []int{2, 1}, size: 3},
	0xF5: {mnemonic: "PUSH AF", size: 1},
	0xF6: {mnemonic: "OR   $1", args: []int{1}, size: 2},
	0xF7: {mnemonic: "RST  30h", size: 1},
	0xF8: {mnemonic: "RET  M", size: 1},
	0xF9: {mnemonic: "LD   SP,HL", size: 1},
	0xFA: {mnemonic: "JP   M,$1$2", args: []int{2, 1}, size: 3},
	0xFB: {mnemonic: "EI", size: 1},
	0xFC: {mnemonic: "CALL M,$1$2", args: []int{2, 1}, size: 3},
	0xFE: {mnemonic: "CP   $1", args: []int{1}, size: 2},
	0xFF: {mnemonic: "RST  38h", size: 1},
}
